config/routes.rb
Rails.application.routes.draw do
  # resources :friends
  post 'friends/new'
  get 'friends/index'
  devise_for :users
  resources :posts
  get 'welcome/index'
  root 'welcome#index'
  resources :conversations, only: [:create,:index] do
		member do
				post :close
		end
	resources :messages, only: [:create]
	end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/friend.rb
class Friend < ApplicationRecord
	def not_friends
		potential = []
		User.all.each do |user|
			if(self.friends_with?(user) != true && self != user && self.friends.include?(user) != true && self.pending_friends.include?(user) != true && self.requested_friends.include?(user) != true)
				potential << user
			end
		end
		potential
	end
	def self.friends_with(friend)
		find_relation(self, friend, status: 2).any?

    end
    def self.find_relation(friendable, friend, status: nil)
      where relation_attributes(friendable, friend, status: status)
    end
 def self.relation_attributes(one, other, status: nil)
      attr = {
        friendable_id: one.id,
        friendable_type: one.class.base_class.name,
        friend_id: other.id
      }

      if status
        attr[:status] = status
      end

      attr
    end
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :set_friend, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index,:show]
  before_action :check_user,only: [:edit,:update,:destroy]

  # GET /friends or /friends.json
  def index
    @users = User.all.where.not(id: current_user) 
  end

  # GET /friends/1 or /friends/1.json
  def show
  end

  # GET /friends/new
  # def new
  #   @friend = Friend.new
  #   # @friend =current_user.friends.build()
    
  # end

  # GET /friends/1/edit
  def edit
  end

  # POST /friends or /friends.json
  def new
    @friend = Friend.new()
    @friend.requestor_id = current_user.id
    @friend.receiver_id = params[:id]
    @friend.status = "pending"
    # @friend =current_user.friends.build(friend_params)
    # @friend.user_id = current_user.id

    respond_to do |format|
      if @friend.save
        format.html { redirect_to @friend, notice: "Friend was successfully created." }
        format.json { render :show, status: :created, location: @friend }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /friends/1 or /friends/1.json
  def update
    respond_to do |format|
      if @friend.update(friend_params)
        format.html { redirect_to @friend, notice: "Friend was successfully updated." }
        format.json { render :show, status: :ok, location: @friend }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friends/1 or /friends/1.json
  def destroy
    @friend.destroy
    respond_to do |format|
      format.html { redirect_to friends_url, notice: "Friend was successfully destroyed." }
      format.json { head :no_content }
    end
  end
  def check_user
    @friend =current_user.friends.find(params[:id])
    redirect_to friends_path,notice:"sorry u can't edit" if @friend.nil?
    
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_friend
      @friend = Friend.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def friend_params
      params.require(:friend).permit(:requestor_id,:receiver_id,:status)
    end
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/views/friends/_form.html.erb
<%= form_with(model: friend) do |form| %>
  <% if friend.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(friend.errors.count, "error") %> prohibited this friend from being saved:</h2>

      <ul>
        <% friend.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= form.text_field :first_name,class:"form-control",placeholder:"First name" %>
  </div>

  <div class="field form-group">
    <%= form.text_field :last_name,class:"form-control",placeholder:"Last name" %>
  </div>

  <div class="field form-group">
    <%= form.text_field :phone_number,class:"form-control",placeholder:"Phone number" %>
  </div>

  <div class="field form-group">
    <%= form.number_field :user_id,class:"form-control",placeholder:"Phone number" %>
  </div>

  <div class="field form-group">
    <%= form.text_area :description,class:"form-control",placeholder:"About yourself" %>
  </div>

  <div class="actions">
    <%= form.submit class:"btn btn-secondary"%>
  </div>
<% end %>

app/views/friends/edit.html.erb
<h1>Editing Friend</h1>

<%= render 'form', friend: @friend %>

<%= link_to 'Show', @friend %> |
<%= link_to 'Back', friends_path %>

app/views/friends/index.html.erb
<h1>Friends</h1>
<% @users.each do |user|%>
	<%= user.email%>
	<br>
	<%= link_to "add friend",friends_new_path(:id=>user.id), class: "btn btn-secondary", remote: true, method: :post%>
	<br>
<%end%>

app/views/friends/new.html.erb
<h1>New Friend</h1>

<%= render 'form', friend: @friend %>

<%= link_to 'Back', friends_path %>

app/views/friends/show.html.erb
<div class="jumbotron">
  <h1 class="display-4"><%= @friend.first_name %> <%= @friend.last_name %></h1>
  <p class="lead"><%= @friend.phone_number %> </p>
  <%= @friend.description %>
  <br>
  	<%= link_to 'Edit', edit_friend_path(@friend),class:"btn btn-info" %> |
	<%= link_to 'Back', friends_path,class: "btn btn-info" %>
</div>