config/routes.rb
Rails.application.routes.draw do
  # resources :friends
  post 'friends/new'
  get 'friends/index'
  devise_for :users
  resources :posts
  get 'welcome/index'
  root 'welcome#index'
  resources :conversations, only: [:create,:index] do
		member do
				post :close
		end
	resources :messages, only: [:create]
	end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/conversation.rb
class Conversation < ApplicationRecord
	has_many :messages, dependent: :destroy
	belongs_to :sender, foreign_key: :sender_id, class_name: "User"
	belongs_to :recipient, foreign_key: :recipient_id, class_name: "User"

	validates :sender_id, uniqueness: { scope: :recipient_id }

	scope :between, -> (sender_id, recipient_id) do
		where(sender_id: sender_id, recipient_id: recipient_id).or(
			where(sender_id: recipient_id, recipient_id: sender_id)
		)
	end

	def self.get(sender_id, recipient_id)
		conversation = between(sender_id, recipient_id).first
		return conversation if conversation.present?

		create(sender_id: sender_id, recipient_id: recipient_id)
	end

	def opposed_user(user)
		user == recipient ? sender : recipient
	end
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
		before_action :authenticate_user!

	# creating a conversation 
	def create

		@conversation = Conversation.get(current_user.id, params[:user_id])
		# verifying if a conversation is present else it will create new session
		add_to_conversations unless conversated?

		respond_to do |format|
			format.js
		end
	end

	# closing the conversation
	def close
		@conversation = Conversation.find(params[:id])

		session[:conversations].delete(@conversation.id)

		respond_to do |format|
			format.js
		end
	end

	# indexing all the conversations between friends 
	def index
		session[:conversations] ||= []

		@users = User.all.where.not(id: current_user)
		@conversations = Conversation.includes(:recipient, :messages).find(session[:conversations])
	end

	private
	#creates a session for a conversation
	def add_to_conversations
		session[:conversations] ||= []
		session[:conversations] << @conversation.id
	end
 
	def conversated?
		session[:conversations].include?(@conversation.id)
	end

end

app/helpers/conversations_helper.rb
module ConversationsHelper
end

app/views/conversations/_conversation.html.erb
<li>
	<div class="panel panel-default" data-conversation-id="<%= conversation.id %>">
		<div class="card-header">
		<div class="panel-heading">
			<h2>
				<%= link_to conversation.opposed_user(user).email, '', class: 'toggle-window' %></h2>
				<%= link_to "x", close_conversation_path(conversation), class: "btn btn-default btn-xs pull-right", remote: true, method: :post %>
		</div>
		</div>

		<div class="panel-body" style="display: none;">
			<div class="messages-list">
				<ul>
					<%= render 'conversations/conversation_content', messages: conversation.messages, user: user %>
				</ul>
			</div>
			<div class="card-footer">
				<%= form_for [conversation, conversation.messages.new], remote: true do |f| %>
					<%= f.hidden_field :user_id, value: user.id %>
					<%= f.text_area :body, class: "form-control" %>
					<%= f.submit "Send", class: "btn btn-success" %>
				<% end %>
			</div>
		</div>
	</div>
</li>

app/views/conversations/_conversation_content.html.erb
<div class="card-body">
	<p class="card-text">
		<% messages.each do |message| %>
			<%= render message, user: user %>
		<% end %>	
	</p>
</div>

app/views/conversations/close.js.erb
$('#conversations-list').find("[data-conversation-id='" + "<%= @conversation.id %>" + "']").parent().remove();

app/views/conversations/create.js.erb
var conversations = $('#conversations-list');
var conversation = conversations.find("[data-conversation-id='" + "<%= @conversation.id %>" + "']");

if (conversation.length !== 1) {
  conversations.append("<%= j(render 'conversations/conversation', conversation: @conversation, user: current_user) %>");
  conversation = conversations.find("[data-conversation-id='" + "<%= @conversation.id %>" + "']");
}

conversation.find('.panel-body').show();

var messages_list = conversation.find('.messages-list');
var height = messages_list[0].scrollHeight;
messages_list.scrollTop(height);

app/views/conversations/index.html.erb
<div class="card">

<div class="row">
	<div class="col-md-3">
    <div class="panel panel-primary">
      <div class="panel-heading">
        <h3 class="panel-title">User list</h3>
      </div>
      <div class="panel-body">
        <ul>
          <% @users.each do |user| %>

            <li>
            	<div class="card"><%= link_to user.email, conversations_path(user_id: user), remote: true, method: :post %></div></li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>

  <div class="col-md-9">
    <ul id="conversations-list">
      <% @conversations.each do |conversation| %>
        <%= render 'conversations/conversation', conversation: conversation, user: current_user %>
      <% end %>
    </ul>
  </div>

  
</div>
</div>